export const states = [
  {
    id: 1,
    name: "Andhra Pradesh",
    districts: [
      { id: 1, name: "Anantapur" },
      { id: 2, name: "Chittoor" },
      { id: 3, name: "East Godavari" },
      { id: 4, name: "Guntur" },
      { id: 5, name: "Krishna" },
      { id: 6, name: "Kurnool" },
      { id: 7, name: "Nellore" },
      { id: 8, name: "Prakasam" },
      { id: 9, name: "Srikakulam" },
      { id: 10, name: "Visakhapatnam" },
      { id: 11, name: "Vizianagaram" },
      { id: 12, name: "West Godavari" },
      { id: 13, name: "YSR Kadapa" },
    ],
  },
  {
    id: 2,
    name: "Arunachal Pradesh",
    districts: [
      { id: 1, name: "Anjaw" },
      { id: 2, name: "Changlang" },
      { id: 3, name: "Dibang Valley" },
      { id: 4, name: "East Kameng" },
      { id: 5, name: "Itanagar" },
      { id: 6, name: "Lohit" },
      { id: 7, name: "Namsai" },
      { id: 8, name: "Papum Pare" },
      { id: 9, name: "Tawang" },
      { id: 10, name: "West Kameng" },
    ],
  },
  {
    id: 3,
    name: "Assam",
    districts: [
      { id: 1, name: "Baksa" },
      { id: 2, name: "Barpeta" },
      { id: 3, name: "Biswanath" },
      { id: 4, name: "Bongaigaon" },
      { id: 5, name: "Cachar" },
      { id: 6, name: "Charaideo" },
      { id: 7, name: "Darrang" },
      { id: 8, name: "Dhemaji" },
      { id: 9, name: "Dhubri" },
      { id: 10, name: "Dibrugarh" },
      { id: 11, name: "Goalpara" },
      { id: 12, name: "Golaghat" },
      { id: 13, name: "Hailakandi" },
      { id: 14, name: "Jorhat" },
      { id: 15, name: "Kamrup" },
      { id: 16, name: "Karbi Anglong" },
      { id: 17, name: "Karimganj" },
      { id: 18, name: "Kokrajhar" },
      { id: 19, name: "Lakhimpur" },
      { id: 20, name: "Majuli" },
      { id: 21, name: "Morigaon" },
      { id: 22, name: "Nagaon" },
      { id: 23, name: "Nalbari" },
      { id: 24, name: "Sivasagar" },
      { id: 25, name: "Sonitpur" },
      { id: 26, name: "South Salmara" },
      { id: 27, name: "Tinsukia" },
      { id: 28, name: "Udalguri" },
    ],
  },
  {
    id: 4,
    name: "Bihar",
    districts: [
      { id: 1, name: "Araria" },
      { id: 2, name: "Arwal" },
      { id: 3, name: "Aurangabad" },
      { id: 4, name: "Banka" },
      { id: 5, name: "Begusarai" },
      { id: 6, name: "Bhagalpur" },
      { id: 7, name: "Bhojpur" },
      { id: 8, name: "Buxar" },
      { id: 9, name: "Darbhanga" },
      { id: 10, name: "East Champaran" },
      { id: 11, name: "Gaya" },
      { id: 12, name: "Gopalganj" },
      { id: 13, name: "Jamui" },
      { id: 14, name: "Jehanabad" },
      { id: 15, name: "Kaimur" },
      { id: 16, name: "Katihar" },
      { id: 17, name: "Khagaria" },
      { id: 18, name: "Kishanganj" },
      { id: 19, name: "Lakhisarai" },
      { id: 20, name: "Madhepura" },
      { id: 21, name: "Madhubani" },
      { id: 22, name: "Munger" },
      { id: 23, name: "Muzaffarpur" },
      { id: 24, name: "Nalanda" },
      { id: 25, name: "Nawada" },
      { id: 26, name: "Patna" },
      { id: 27, name: "Purnia" },
      { id: 28, name: "Rohtas" },
      { id: 29, name: "Saharsa" },
      { id: 30, name: "Samastipur" },
      { id: 31, name: "Saran" },
      { id: 32, name: "Sheikhpura" },
      { id: 33, name: "Sheohar" },
      { id: 34, name: "Sitamarhi" },
      { id: 35, name: "Siwan" },
      { id: 36, name: "Supaul" },
      { id: 37, name: "Vaishali" },
      { id: 38, name: "West Champaran" },
    ],
  },
  {
    id: 5,
    name: "Chhattisgarh",
    districts: [
      { id: 1, name: "Balod" },
      { id: 2, name: "Baloda Bazar" },
      { id: 3, name: "Balrampur" },
      { id: 4, name: "Bastar" },
      { id: 5, name: "Bemetara" },
      { id: 6, name: "Bijapur" },
      { id: 7, name: "Bilaspur" },
      { id: 8, name: "Dantewada" },
      { id: 9, name: "Dhamtari" },
      { id: 10, name: "Durg" },
      { id: 11, name: "Gariaband" },
      { id: 12, name: "Janjgir-Champa" },
      { id: 13, name: "Jashpur" },
      { id: 14, name: "Kabirdham" },
      { id: 15, name: "Kanker" },
      { id: 16, name: "Kondagaon" },
      { id: 17, name: "Korba" },
      { id: 18, name: "Koriya" },
      { id: 19, name: "Mahasamund" },
      { id: 20, name: "Mungeli" },
      { id: 21, name: "Narayanpur" },
      { id: 22, name: "Raigarh" },
      { id: 23, name: "Raipur" },
      { id: 24, name: "Rajnandgaon" },
      { id: 25, name: "Sukma" },
      { id: 26, name: "Surajpur" },
      { id: 27, name: "Surguja" },
    ],
  },
  {
    id: 6,
    name: "Goa",
    districts: [
      { id: 1, name: "North Goa" },
      { id: 2, name: "South Goa" },
    ],
  },
  {
    id: 7,
    name: "Gujarat",
    districts: [
      { id: 1, name: "Ahmedabad" },
      { id: 2, name: "Amreli" },
      { id: 3, name: "Anand" },
      { id: 4, name: "Aravalli" },
      { id: 5, name: "Banaskantha" },
      { id: 6, name: "Bharuch" },
      { id: 7, name: "Bhavnagar" },
      { id: 8, name: "Botad" },
      { id: 9, name: "Chhota Udaipur" },
      { id: 10, name: "Dahod" },
      { id: 11, name: "Dang" },
      { id: 12, name: "Devbhoomi Dwarka" },
      { id: 13, name: "Gandhinagar" },
      { id: 14, name: "Gir Somnath" },
      { id: 15, name: "Jamnagar" },
      { id: 16, name: "Junagadh" },
      { id: 17, name: "Kheda" },
      { id: 18, name: "Kutch" },
      { id: 19, name: "Mahisagar" },
      { id: 20, name: "Mehsana" },
      { id: 21, name: "Morbi" },
      { id: 22, name: "Narmada" },
      { id: 23, name: "Navsari" },
      { id: 24, name: "Panchmahal" },
      { id: 25, name: "Patan" },
      { id: 26, name: "Porbandar" },
      { id: 27, name: "Rajkot" },
      { id: 28, name: "Sabarkantha" },
      { id: 29, name: "Surat" },
      { id: 30, name: "Surendranagar" },
      { id: 31, name: "Tapi" },
      { id: 32, name: "Vadodara" },
      { id: 33, name: "Valsad" },
    ],
  },
  {
    id: 8,
    name: "Haryana",
    districts: [
      { id: 1, name: "Ambala" },
      { id: 2, name: "Bhiwani" },
      { id: 3, name: "Charkhi Dadri" },
      { id: 4, name: "Faridabad" },
      { id: 5, name: "Fatehabad" },
      { id: 6, name: "Gurugram" },
      { id: 7, name: "Hisar" },
      { id: 8, name: "Jhajjar" },
      { id: 9, name: "Jind" },
      { id: 10, name: "Kaithal" },
      { id: 11, name: "Karnal" },
      { id: 12, name: "Kurukshetra" },
      { id: 13, name: "Mahendragarh" },
      { id: 14, name: "Nuh" },
      { id: 15, name: "Palwal" },
      { id: 16, name: "Panchkula" },
      { id: 17, name: "Panipat" },
      { id: 18, name: "Rewari" },
      { id: 19, name: "Rohtak" },
      { id: 20, name: "Sirsa" },
      { id: 21, name: "Sonipat" },
      { id: 22, name: "Yamunanagar" },
    ],
  },
  {
    id: 9,
    name: "Himachal Pradesh",
    districts: [
      { id: 1, name: "Bilaspur" },
      { id: 2, name: "Chamba" },
      { id: 3, name: "Hamirpur" },
      { id: 4, name: "Kangra" },
      { id: 5, name: "Kinnaur" },
      { id: 6, name: "Kullu" },
      { id: 7, name: "Lahaul and Spiti" },
      { id: 8, name: "Mandi" },
      { id: 9, name: "Shimla" },
      { id: 10, name: "Sirmaur" },
      { id: 11, name: "Solan" },
      { id: 12, name: "Una" },
    ],
  },
  {
    id: 10,
    name: "Jharkhand",
    districts: [
      { id: 1, name: "Bokaro" },
      { id: 2, name: "Chatra" },
      { id: 3, name: "Deoghar" },
      { id: 4, name: "Dhanbad" },
      { id: 5, name: "Dumka" },
      { id: 6, name: "East Singhbhum" },
      { id: 7, name: "Garhwa" },
      { id: 8, name: "Giridih" },
      { id: 9, name: "Godda" },
      { id: 10, name: "Gumla" },
      { id: 11, name: "Hazaribagh" },
      { id: 12, name: "Jamtara" },
      { id: 13, name: "Khunti" },
      { id: 14, name: "Koderma" },
      { id: 15, name: "Latehar" },
      { id: 16, name: "Lohardaga" },
      { id: 17, name: "Pakur" },
      { id: 18, name: "Palamu" },
      { id: 19, name: "Ramgarh" },
      { id: 20, name: "Ranchi" },
      { id: 21, name: "Sahibganj" },
      { id: 22, name: "Seraikela Kharsawan" },
      { id: 23, name: "Simdega" },
      { id: 24, name: "West Singhbhum" },
    ],
  },
  {
    id: 11,
    name: "Karnataka",
    districts: [
      { id: 1, name: "Bagalkot" },
      { id: 2, name: "Ballari" },
      { id: 3, name: "Belagavi" },
      { id: 4, name: "Bengaluru Rural" },
      { id: 5, name: "Bengaluru Urban" },
      { id: 6, name: "Bidar" },
      { id: 7, name: "Chamarajanagar" },
      { id: 8, name: "Chikballapur" },
      { id: 9, name: "Chikkamagaluru" },
      { id: 10, name: "Chitradurga" },
      { id: 11, name: "Dakshina Kannada" },
      { id: 12, name: "Davanagere" },
      { id: 13, name: "Dharwad" },
      { id: 14, name: "Gadag" },
      { id: 15, name: "Hassan" },
      { id: 16, name: "Haveri" },
      { id: 17, name: "Kalaburagi" },
      { id: 18, name: "Kodagu" },
      { id: 19, name: "Kolar" },
      { id: 20, name: "Koppal" },
      { id: 21, name: "Mandya" },
      { id: 22, name: "Mysuru" },
      { id: 23, name: "Raichur" },
      { id: 24, name: "Ramanagara" },
      { id: 25, name: "Shivamogga" },
      { id: 26, name: "Tumakuru" },
      { id: 27, name: "Udupi" },
      { id: 28, name: "Uttara Kannada" },
      { id: 29, name: "Vijayanagara" },
      { id: 30, name: "Yadgir" },
    ],
  },
  {
    id: 12,
    name: "Kerala",
    districts: [
      { id: 1, name: "Alappuzha" },
      { id: 2, name: "Ernakulam" },
      { id: 3, name: "Idukki" },
      { id: 4, name: "Kannur" },
      { id: 5, name: "Kasaragod" },
      { id: 6, name: "Kollam" },
      { id: 7, name: "Kottayam" },
      { id: 8, name: "Kozhikode" },
      { id: 9, name: "Malappuram" },
      { id: 10, name: "Palakkad" },
      { id: 11, name: "Pathanamthitta" },
      { id: 12, name: "Thiruvananthapuram" },
      { id: 13, name: "Thrissur" },
      { id: 14, name: "Wayanad" },
    ],
  },
  {
    id: 13,
    name: "Madhya Pradesh",
    districts: [
      { id: 1, name: "Agar Malwa" },
      { id: 2, name: "Alirajpur" },
      { id: 3, name: "Anuppur" },
      { id: 4, name: "Ashoknagar" },
      { id: 5, name: "Balaghat" },
      { id: 6, name: "Barwani" },
      { id: 7, name: "Betul" },
      { id: 8, name: "Bhind" },
      { id: 9, name: "Bhopal" },
      { id: 10, name: "Burhanpur" },
      { id: 11, name: "Chhatarpur" },
      { id: 12, name: "Chhindwara" },
      { id: 13, name: "Damoh" },
      { id: 14, name: "Datia" },
      { id: 15, name: "Dewas" },
      { id: 16, name: "Dhar" },
      { id: 17, name: "Dindori" },
      { id: 18, name: "Guna" },
      { id: 19, name: "Gwalior" },
      { id: 20, name: "Harda" },
      { id: 21, name: "Hoshangabad" },
      { id: 22, name: "Indore" },
      { id: 23, name: "Jabalpur" },
      { id: 24, name: "Jhabua" },
      { id: 25, name: "Katni" },
      { id: 26, name: "Khandwa" },
      { id: 27, name: "Khargone" },
      { id: 28, name: "Mandla" },
      { id: 29, name: "Mandsaur" },
      { id: 30, name: "Morena" },
      { id: 31, name: "Narsinghpur" },
      { id: 32, name: "Neemuch" },
      { id: 33, name: "Panna" },
      { id: 34, name: "Raisen" },
      { id: 35, name: "Rajgarh" },
      { id: 36, name: "Ratlam" },
      { id: 37, name: "Rewa" },
      { id: 38, name: "Sagar" },
      { id: 39, name: "Satna" },
      { id: 40, name: "Sehore" },
      { id: 41, name: "Seoni" },
      { id: 42, name: "Shahdol" },
      { id: 43, name: "Shajapur" },
      { id: 44, name: "Sheopur" },
      { id: 45, name: "Shivpuri" },
      { id: 46, name: "Sidhi" },
      { id: 47, name: "Singrauli" },
      { id: 48, name: "Tikamgarh" },
      { id: 49, name: "Ujjain" },
      { id: 50, name: "Umaria" },
      { id: 51, name: "Vidisha" },
    ],
  },
  {
    id: 14,
    name: "Maharashtra",
    districts: [
      { id: 1, name: "Ahmednagar" },
      { id: 2, name: "Akola" },
      { id: 3, name: "Amravati" },
      { id: 4, name: "Aurangabad" },
      { id: 5, name: "Beed" },
      { id: 6, name: "Bhandara" },
      { id: 7, name: "Buldhana" },
      { id: 8, name: "Chandrapur" },
      { id: 9, name: "Dhule" },
      { id: 10, name: "Gadchiroli" },
      { id: 11, name: "Gondia" },
      { id: 12, name: "Hingoli" },
      { id: 13, name: "Jalgaon" },
      { id: 14, name: "Jalna" },
      { id: 15, name: "Kolhapur" },
      { id: 16, name: "Latur" },
      { id: 17, name: "Mumbai City" },
      { id: 18, name: "Mumbai Suburban" },
      { id: 19, name: "Nagpur" },
      { id: 20, name: "Nanded" },
      { id: 21, name: "Nandurbar" },
      { id: 22, name: "Nashik" },
      { id: 23, name: "Osmanabad" },
      { id: 24, name: "Palghar" },
      { id: 25, name: "Parbhani" },
      { id: 26, name: "Pune" },
      { id: 27, name: "Raigad" },
      { id: 28, name: "Ratnagiri" },
      { id: 29, name: "Sangli" },
      { id: 30, name: "Satara" },
      { id: 31, name: "Sindhudurg" },
      { id: 32, name: "Solapur" },
      { id: 33, name: "Thane" },
      { id: 34, name: "Wardha" },
      { id: 35, name: "Washim" },
      { id: 36, name: "Yavatmal" },
    ],
  },
  {
    id: 15,
    name: "Manipur",
    districts: [
      { id: 1, name: "Bishnupur" },
      { id: 2, name: "Chandel" },
      { id: 3, name: "Churachandpur" },
      { id: 4, name: "Imphal East" },
      { id: 5, name: "Imphal West" },
      { id: 6, name: "Jiribam" },
      { id: 7, name: "Kakching" },
      { id: 8, name: "Kamjong" },
      { id: 9, name: "Kangpokpi" },
      { id: 10, name: "Noney" },
      { id: 11, name: "Pherzawl" },
      { id: 12, name: "Senapati" },
      { id: 13, name: "Tamenglong" },
      { id: 14, name: "Tengnoupal" },
      { id: 15, name: "Thoubal" },
      { id: 16, name: "Ukhrul" },
    ],
  },
  {
    id: 16,
    name: "Meghalaya",
    districts: [
      { id: 1, name: "East Garo Hills" },
      { id: 2, name: "East Jaintia Hills" },
      { id: 3, name: "East Khasi Hills" },
      { id: 4, name: "North Garo Hills" },
      { id: 5, name: "Ri Bhoi" },
      { id: 6, name: "South Garo Hills" },
      { id: 7, name: "South West Garo Hills" },
      { id: 8, name: "South West Khasi Hills" },
      { id: 9, name: "West Garo Hills" },
      { id: 10, name: "West Jaintia Hills" },
      { id: 11, name: "West Khasi Hills" },
    ],
  },
  {
    id: 17,
    name: "Mizoram",
    districts: [
      { id: 1, name: "Aizawl" },
      { id: 2, name: "Champhai" },
      { id: 3, name: "Hnahthial" },
      { id: 4, name: "Khawzawl" },
      { id: 5, name: "Kolasib" },
      { id: 6, name: "Lawngtlai" },
      { id: 7, name: "Lunglei" },
      { id: 8, name: "Mamit" },
      { id: 9, name: "Saiha" },
      { id: 10, name: "Saitual" },
      { id: 11, name: "Serchhip" },
    ],
  },
  {
    id: 18,
    name: "Nagaland",
    districts: [
      { id: 1, name: "Chümoukedima" },
      { id: 2, name: "Dimapur" },
      { id: 3, name: "Kiphire" },
      { id: 4, name: "Kohima" },
      { id: 5, name: "Longleng" },
      { id: 6, name: "Mokokchung" },
      { id: 7, name: "Mon" },
      { id: 8, name: "Niuland" },
      { id: 9, name: "Noklak" },
      { id: 10, name: "Peren" },
      { id: 11, name: "Phek" },
      { id: 12, name: "Tseminyu" },
      { id: 13, name: "Tuensang" },
      { id: 14, name: "Wokha" },
      { id: 15, name: "Zünheboto" },
    ],
  },
  {
    id: 19,
    name: "Odisha",
    districts: [
      { id: 1, name: "Angul" },
      { id: 2, name: "Balangir" },
      { id: 3, name: "Balasore" },
      { id: 4, name: "Bargarh" },
      { id: 5, name: "Bhadrak" },
      { id: 6, name: "Boudh" },
      { id: 7, name: "Cuttack" },
      { id: 8, name: "Deogarh" },
      { id: 9, name: "Dhenkanal" },
      { id: 10, name: "Gajapati" },
      { id: 11, name: "Ganjam" },
      { id: 12, name: "Jagatsinghpur" },
      { id: 13, name: "Jajpur" },
      { id: 14, name: "Jharsuguda" },
      { id: 15, name: "Kalahandi" },
      { id: 16, name: "Kandhamal" },
      { id: 17, name: "Kendrapara" },
      { id: 18, name: "Kendujhar (Keonjhar)" },
      { id: 19, name: "Khordha" },
      { id: 20, name: "Koraput" },
      { id: 21, name: "Malkangiri" },
      { id: 22, name: "Mayurbhanj" },
      { id: 23, name: "Nabarangpur" },
      { id: 24, name: "Nayagarh" },
      { id: 25, name: "Nuapada" },
      { id: 26, name: "Puri" },
      { id: 27, name: "Rayagada" },
      { id: 28, name: "Sambalpur" },
      { id: 29, name: "Subarnapur (Sonepur)" },
      { id: 30, name: "Sundargarh" },
    ],
  },
  {
    id: 20,
    name: "Punjab",
    districts: [
      { id: 1, name: "Amritsar" },
      { id: 2, name: "Barnala" },
      { id: 3, name: "Bathinda" },
      { id: 4, name: "Faridkot" },
      { id: 5, name: "Fatehgarh Sahib" },
      { id: 6, name: "Fazilka" },
      { id: 7, name: "Ferozepur" },
      { id: 8, name: "Gurdaspur" },
      { id: 9, name: "Hoshiarpur" },
      { id: 10, name: "Jalandhar" },
      { id: 11, name: "Kapurthala" },
      { id: 12, name: "Ludhiana" },
      { id: 13, name: "Malerkotla" },
      { id: 14, name: "Mansa" },
      { id: 15, name: "Moga" },
      { id: 16, name: "Mohali" },
      { id: 17, name: "Muktsar" },
      { id: 18, name: "Nawanshahr (Shahid Bhagat Singh Nagar)" },
      { id: 19, name: "Pathankot" },
      { id: 20, name: "Patiala" },
      { id: 21, name: "Rupnagar" },
      { id: 22, name: "Sangrur" },
      { id: 23, name: "Tarn Taran" },
    ],
  },
  {
    id: 21,
    name: "Rajasthan",
    districts: [
      { id: 1, name: "Ajmer" },
      { id: 2, name: "Alwar" },
      { id: 3, name: "Banswara" },
      { id: 4, name: "Baran" },
      { id: 5, name: "Barmer" },
      { id: 6, name: "Bharatpur" },
      { id: 7, name: "Bhilwara" },
      { id: 8, name: "Bikaner" },
      { id: 9, name: "Bundi" },
      { id: 10, name: "Chittorgarh" },
      { id: 11, name: "Churu" },
      { id: 12, name: "Dausa" },
      { id: 13, name: "Dholpur" },
      { id: 14, name: "Dungarpur" },
      { id: 15, name: "Hanumangarh" },
      { id: 16, name: "Jaipur" },
      { id: 17, name: "Jaisalmer" },
      { id: 18, name: "Jalore" },
      { id: 19, name: "Jhalawar" },
      { id: 20, name: "Jhunjhunu" },
      { id: 21, name: "Jodhpur" },
      { id: 22, name: "Karauli" },
      { id: 23, name: "Kota" },
      { id: 24, name: "Nagaur" },
      { id: 25, name: "Pali" },
      { id: 26, name: "Pratapgarh" },
      { id: 27, name: "Rajsamand" },
      { id: 28, name: "Sawai Madhopur" },
      { id: 29, name: "Sikar" },
      { id: 30, name: "Sirohi" },
      { id: 31, name: "Sri Ganganagar" },
      { id: 32, name: "Tonk" },
      { id: 33, name: "Udaipur" },
    ],
  },
  {
    id: 22,
    name: "Sikkim",
    districts: [
      { id: 1, name: "East Sikkim" },
      { id: 2, name: "North Sikkim" },
      { id: 3, name: "South Sikkim" },
      { id: 4, name: "West Sikkim" },
    ],
  },
  {
    id: 23,
    name: "Tamil Nadu",
    districts: [
      { id: 1, name: "Ariyalur" },
      { id: 2, name: "Chengalpattu" },
      { id: 3, name: "Chennai" },
      { id: 4, name: "Coimbatore" },
      { id: 5, name: "Cuddalore" },
      { id: 6, name: "Dharmapuri" },
      { id: 7, name: "Dindigul" },
      { id: 8, name: "Erode" },
      { id: 9, name: "Kallakurichi" },
      { id: 10, name: "Kanchipuram" },
      { id: 11, name: "Kanyakumari" },
      { id: 12, name: "Karur" },
      { id: 13, name: "Krishnagiri" },
      { id: 14, name: "Madurai" },
      { id: 15, name: "Nagapattinam" },
      { id: 16, name: "Namakkal" },
      { id: 17, name: "Nilgiris" },
      { id: 18, name: "Perambalur" },
      { id: 19, name: "Pudukkottai" },
      { id: 20, name: "Ramanathapuram" },
      { id: 21, name: "Ranipet" },
      { id: 22, name: "Salem" },
      { id: 23, name: "Sivaganga" },
      { id: 24, name: "Tenkasi" },
      { id: 25, name: "Thanjavur" },
      { id: 26, name: "Theni" },
      { id: 27, name: "Thoothukudi" },
      { id: 28, name: "Tiruchirappalli" },
      { id: 29, name: "Tirunelveli" },
      { id: 30, name: "Vellore" },
      { id: 31, name: "Viluppuram" },
      { id: 32, name: "Virudhunagar" },
    ],
  },
  {
    id: 24,
    name: "Telangana",
    districts: [
      { id: 1, name: "Adilabad" },
      { id: 2, name: "Bhadradri Kothagudem" },
      { id: 3, name: "Hyderabad" },
      { id: 4, name: "Jagtial" },
      { id: 5, name: "Jangaon" },
      { id: 6, name: "Jayashankar Bhupalpally" },
      { id: 7, name: "Jogulamba Gadwal" },
      { id: 8, name: "Kamareddy" },
      { id: 9, name: "Karimnagar" },
      { id: 10, name: "Khammam" },
      { id: 11, name: "Komaram Bheem Asifabad" },
      { id: 12, name: "Mahabubabad" },
      { id: 13, name: "Mahabubnagar" },
      { id: 14, name: "Mancherial" },
      { id: 15, name: "Medak" },
      { id: 16, name: "Medchal–Malkajgiri" },
      { id: 17, name: "Mulugu" },
      { id: 18, name: "Nagarkurnool" },
      { id: 19, name: "Nalgonda" },
      { id: 20, name: "Narayanpet" },
      { id: 21, name: "Nirmal" },
      { id: 22, name: "Nizamabad" },
      { id: 23, name: "Peddapalli" },
      { id: 24, name: "Rajanna Sircilla" },
      { id: 25, name: "Rangareddy" },
      { id: 26, name: "Sangareddy" },
      { id: 27, name: "Siddipet" },
      { id: 28, name: "Suryapet" },
      { id: 29, name: "Vikarabad" },
      { id: 30, name: "Wanaparthy" },
      { id: 31, name: "Warangal Rural" },
      { id: 32, name: "Warangal Urban" },
      { id: 33, name: "Yadadri Bhuvanagiri" },
    ],
  },
  {
    id: 25,
    name: "Tripura",
    districts: [
      { id: 1, name: "Dhalai" },
      { id: 2, name: "Gomati" },
      { id: 3, name: "Khowai" },
      { id: 4, name: "North Tripura" },
      { id: 5, name: "Sepahijala" },
      { id: 6, name: "South Tripura" },
      { id: 7, name: "Unakoti" },
      { id: 8, name: "West Tripura" },
    ],
  },
  {
    id: 26,
    name: "Uttar Pradesh",
    districts: [
      { id: 1, name: "Agra" },
      { id: 2, name: "Aligarh" },
      { id: 3, name: "Ambedkar Nagar" },
      { id: 4, name: "Amethi" },
      { id: 5, name: "Amroha" },
      { id: 6, name: "Auraiya" },
      { id: 7, name: "Ayodhya" },
      { id: 8, name: "Azamgarh" },
      { id: 9, name: "Baghpat" },
      { id: 10, name: "Bahraich" },
      { id: 11, name: "Ballia" },
      { id: 12, name: "Balrampur" },
      { id: 13, name: "Banda" },
      { id: 14, name: "Barabanki" },
      { id: 15, name: "Bareilly" },
      { id: 16, name: "Basti" },
      { id: 17, name: "Bhadohi" },
      { id: 18, name: "Bijnor" },
      { id: 19, name: "Budaun" },
      { id: 20, name: "Bulandshahr" },
      { id: 21, name: "Chandauli" },
      { id: 22, name: "Chitrakoot" },
      { id: 23, name: "Deoria" },
      { id: 24, name: "Etah" },
      { id: 25, name: "Etawah" },
      { id: 26, name: "Farrukhabad" },
      { id: 27, name: "Fatehpur" },
      { id: 28, name: "Firozabad" },
      { id: 29, name: "Gautam Buddha Nagar" },
      { id: 30, name: "Ghaziabad" },
      { id: 31, name: "Ghazipur" },
      { id: 32, name: "Gonda" },
      { id: 33, name: "Gorakhpur" },
      { id: 34, name: "Hamirpur" },
      { id: 35, name: "Hardoi" },
      { id: 36, name: "Hathras" },
      { id: 37, name: "Jalaun" },
      { id: 38, name: "Jaunpur" },
      { id: 39, name: "Jhansi" },
      { id: 40, name: "Kannauj" },
      { id: 41, name: "Kanpur Dehat" },
      { id: 42, name: "Kanpur Nagar" },
      { id: 43, name: "Kasganj" },
      { id: 44, name: "Kaushambi" },
      { id: 45, name: "Kushinagar" },
      { id: 46, name: "Lakhimpur Kheri" },
      { id: 47, name: "Lalitpur" },
      { id: 48, name: "Lucknow" },
      { id: 49, name: "Maharajganj" },
      { id: 50, name: "Mahoba" },
      { id: 51, name: "Mainpuri" },
      { id: 52, name: "Mathura" },
      { id: 53, name: "Mau" },
      { id: 54, name: "Meerut" },
      { id: 55, name: "Mirzapur" },
      { id: 56, name: "Moradabad" },
      { id: 57, name: "Muzaffarnagar" },
      { id: 58, name: "Pilibhit" },
      { id: 59, name: "Pratapgarh" },
      { id: 60, name: "Prayagraj" },
      { id: 61, name: "Raebareli" },
      { id: 62, name: "Rampur" },
      { id: 63, name: "Saharanpur" },
      { id: 64, name: "Sambhal" },
      { id: 65, name: "Sant Kabir Nagar" },
      { id: 66, name: "Shahjahanpur" },
      { id: 67, name: "Shamli" },
      { id: 68, name: "Shrawasti" },
      { id: 69, name: "Siddharthnagar" },
      { id: 70, name: "Sitapur" },
      { id: 71, name: "Sonbhadra" },
      { id: 72, name: "Sultanpur" },
      { id: 73, name: "Unnao" },
      { id: 74, name: "Varanasi" },
    ],
  },
  {
    id: 27,
    name: "Uttarakhand",
    districts: [
      { id: 1, name: "Almora" },
      { id: 2, name: "Bageshwar" },
      { id: 3, name: "Chamoli" },
      { id: 4, name: "Champawat" },
      { id: 5, name: "Dehradun" },
      { id: 6, name: "Haridwar" },
      { id: 7, name: "Nainital" },
      { id: 8, name: "Pauri Garhwal" },
      { id: 9, name: "Pithoragarh" },
      { id: 10, name: "Rudraprayag" },
      { id: 11, name: "Tehri Garhwal" },
      { id: 12, name: "Udham Singh Nagar" },
      { id: 13, name: "Uttarkashi" },
    ],
  },
  {
    id: 28,
    name: "West Bengal",
    districts: [
      { id: 1, name: "Alipurduar" },
      { id: 2, name: "Bankura" },
      { id: 3, name: "Birbhum" },
      { id: 4, name: "Cooch Behar" },
      { id: 5, name: "Dakshin Dinajpur" },
      { id: 6, name: "Darjeeling" },
      { id: 7, name: "Hooghly" },
      { id: 8, name: "Howrah" },
      { id: 9, name: "Jalpaiguri" },
      { id: 10, name: "Jhargram" },
      { id: 11, name: "Kalimpong" },
      { id: 12, name: "Kolkata" },
      { id: 13, name: "Malda" },
      { id: 14, name: "Murshidabad" },
      { id: 15, name: "Nadia" },
      { id: 16, name: "North 24 Parganas" },
      { id: 17, name: "Paschim Bardhaman" },
      { id: 18, name: "Paschim Medinipur" },
      { id: 19, name: "Purba Bardhaman" },
      { id: 20, name: "Purba Medinipur" },
      { id: 21, name: "Purulia" },
      { id: 22, name: "South 24 Parganas" },
      { id: 23, name: "Uttar Dinajpur" },
    ],
  },
];
